INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_COUNTRY) VALUES (1, 'GOOGLE', 'google@google.com', '123 123-1234', 'Google Street 1', 'Palo Alto', 'United States');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_COUNTRY) VALUES (2, 'ORACLE', 'oracle@oracle.com', '098 098-7654', 'Oracle Street 2', 'Redwood', 'United States');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_COUNTRY) VALUES (3, 'MICROSOFT', 'microsoft@microsoft.com', '456 456-7890', 'Microsoft Street 3', 'San Francisco', 'United States');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_COUNTRY) VALUES (4, 'IBM', 'ibm@ibm.com', '734 734-8965', 'IBM Street 4', 'Denver', 'United States');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, ADDRESS_STREET, ADDRESS_CITY, ADDRESS_COUNTRY) VALUES (5, 'FACEBOOK', 'facebook@facebook.com', '987 987-4567', 'Facebook Street 5', 'San Diego', 'United States');

INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (1, 'Larry Page', 0);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (1, 'Sergey Brin', 1);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (2, 'Larry Ellison', 0);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (2, 'Jeffrey O. Henley', 1);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (3, 'Bill Gates', 0);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (3, 'Paul Allen', 1);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (4, 'Thomas J. Watson', 0);
INSERT INTO TB_COMPANY_OWNER (COMPANY_ID, OWNER_NAME, OWNER_ORDER) VALUES (5, 'Mark Zukeberg', 0);